/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 *
 * Copyright 2017 Nextdoor.com, Inc
 *
 */

package com.nextdoor.bender.config;

public class ConfigurationException extends RuntimeException {
  /**
   * Generated by eclipse
   */
  private static final long serialVersionUID = 7837054786370238468L;

  public ConfigurationException(String reason, Exception e) {
    super(reason, e);
  }

  public ConfigurationException(String reason) {
    super(reason);
  }
}
